name: u24_element_build_call

on:
  pull_request:
  push:
  workflow_dispatch:

anchor-dev-build-call: &dev-build-call
  uses: yambottle/djsciops-cicd/.github/workflows/u24_element_build.yaml@main

anchor-test-build-call: &test-build-call
  uses: yambottle/djsciops-cicd/.github/workflows/u24_element_build.yaml@main

anchor-prod-build-call: &prod-build-call
  uses: dj-sciops/djsciops-cicd/.github/workflows/u24_element_build.yaml@main

jobs:
  # call_u24_elements_build_alpine:
  #   !!merge <<: *$STAGE-build-call
  #   with:
  #     py_ver: 3.9
  #     image: djbase
  skip_build:
    runs-on: ubuntu-latest
    steps:
      - name: Skip build
        run: |
          echo "Build finished"
          echo ${{github.ref}}
          echo ${{github.event.workflow_run.event}}