# docker-compose -f ./docker/docker-compose-dev.yaml up -d --build
# docker-compose -f ./docker/docker-compose-dev.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    container_name: workflow-deeplabcut-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-deeplabcut/docker/Dockerfile.dev
    env_file: .env
    image: workflow-deeplabcut-dev:0.1.0a4
    container_name: workflow-deeplabcut-dev
    environment:
      - TEST_DATA_DIR=/main/test_data/workflow_dlc_data1/,/main/test_data/workflow_dlc_data2/
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../../element-lab:/main/element-lab
      - ../../element-animal:/main/element-animal
      - ../../element-session:/main/element-session
      - ../../element-deeplabcut:/main/element-deeplabcut
      - ..:/main/workflow-deeplabcut
    depends_on:
      db:
        condition: service_healthy
networks:
  main:
