name: Development
on:
  pull_request:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
  
jobs:
  call_u24_elements_pypi_alpine:
    uses: dj-sciops/djsciops-cicd/.github/workflows/u24_elements.yaml@main
    with:
      py_ver: 3.9
      dist: alpine
      image: djbase