name: u24_element_build_call
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  # call_u24_elements_build_alpine:
  #   !!merge <<: *dev-build-call
  #   with:
  #     py_ver: 3.9
  #     image: djbase
  skip_build:
    runs-on: ubuntu-latest
    steps:
      - name: Skip build
        run: |-
          echo "Build finished"
          echo ${{github.ref}}
          echo ${{github.event.workflow_run.event}}
