name: u24_element_mkdocs-build
on:
  push:
    # tags:
    #   - \d+\.\d+\.\d+
jobs:
  publish-docs:
    if: |
      github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      DOCKER_CLIENT_TIMEOUT: "120"
      COMPOSE_HTTP_TIMEOUT: "120"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        run: |
          ELEMENT_HYPHENS=${GITHUB_REPOSITORY##*/}
          ELEMENT_UNDERSCORES=${ELEMENT_HYPHENS//-/_}
          export MODE=PUSH
          export PACKAGE=${ELEMENT_UNDERSCORES}
          export UPSTREAM_REPO=https://action-user:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          export HOST_UID=$(id -u)
          docker compose -f docs/docker-compose.yaml up --exit-code-from docs --build