name: u24_element_release_call
on:
  workflow_run:
    workflows: ["u24_element_build_call"]
    types:
      - completed
jobs:
  condition_check:
    runs-on: ubuntu-latest
    steps:
      - name: condition_check
        run: |
          echo ${{github.event.workflow_run.conclusion}}
          echo ${{github.ref}}
          echo ${{github.repository.git_refs_url}}
          echo ${{github.repository.git_tags_url}}
          echo ${{github.event.workflow_run.event}}
          echo ${{github}}
          echo $GITHUB_CONTEXT
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
  test_call_u24_elements_release_alpine:
    if: ${{ (github.event.workflow_run.conclusion == 'success') && ( contains(github.ref, 'test') || (github.event.workflow_run.event == 'pull_request')) }}
    uses: yambottle/djsciops-cicd/.github/workflows/u24_element_release.yaml@main
    with:
      TWINE_REPO: testpypi
    secrets:
      TWINE_USERNAME: ${{secrets.TWINE_TEST_USERNAME}}
      TWINE_PASSWORD: ${{secrets.TWINE_TEST_PASSWORD}}
  call_u24_elements_release_alpine:
    if: ${{ (github.event.workflow_run.conclusion == 'success') && startsWith(github.ref, 'refs/tags') && !contains(github.ref, 'test') }}
    uses: yambottle/djsciops-cicd/.github/workflows/u24_element_release.yaml@main
    secrets:
      TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
      TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
